### ISSUE TITLE
Improve pre-creation of virtual helm repository

### ISSUE THREAD

**Issue by andreikom** [jfrog/helm-hub-sync#14]
Currently the plugin expects the helm virtual repository to be used by it to be *pre-created*, otherwise you will run into a 400 error from Artifactory when trying to activate the plugin.

The request is to have the plugin be able to create the virtual helm repository by itself + document it in the README. 

Another suggestion is to have retry ability for HTTP client (in case some kind of an error happened once and the next request can and will succeed).

**Comment by rimusz** [comment]
Closing the issue as this repository got deprecated
