### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by zendril** [jfrog/helm-hub-sync#17]
We would be running this inside our internal kubernetes cluster which does not have direct access to the internet in order to read from hub.helm.sh.

I don't see one, but does this support setting a proxy, or support proxy env vars http_proxy, https_proxy, etc?

**Comment by zendril** [comment]
I see it is using net/http. Going to try to set HTTP_PROXY, HTTPS_PROXY and see if it honors it. Will report back after that.

**Comment by zendril** [comment]
Looks like it does honor them, however there is no way to specify it in the current chart.

Need to update the the config template to allow HTTP_PROXY and HTTPS_PROXY variables.
Also need to allow specifying a NetworkPolicy, as for us we have a default policy of DenyAll. This means explicit egress must be setup.

**Comment by rimusz** [comment]
Closing the issue as this repository got deprecated
